### ISSUE TITLE
[Actions BUG] releases being marked as draft

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5WS#26]

**Comment by PhlexPlexico** [comment]
So the reason why I have these kept as drafts is because I don't actually want to make a release every time, to be honest. The way it presents the title of the release, and the tag itself, isn't really.... Smart compared to how I've done it after this one. 

It may require a bit more work than just setting the draft, but I would prefer setting it as a prerelease like this - https://github.com/gamestabled/OoT3D_Randomizer/blob/ac0243ad68f69b604d710c6abc06f95273b567b6/.github/workflows/create_nightly.yml#L22-L42

Of course without the downloads in the body, haha. So maybe making it a bit more informative would be better right now :)

**Comment by kubo6472** [comment]
Just uploading the compiled asset to actions would be enough tbh. just that every sourcepawn I compiled to this date had some issues compared to the ones I got from your releases. All I was gonna ask, was if you planned on releasing Fix check for client num release since I use the coaches on almost every match now.

**Comment by PhlexPlexico** [comment]
Ah! I see what you mean. I thought I had it uploading to artifacts as well. The only reason I don't have them listed as releases right now is due to the fact that I haven't tested it, so I don't know if they're stable enough yet or not. I'll go mark this one as a pre-release for now, and will update the action to start providing pre-releases instead :)

**Comment by kubo6472** [comment]
Thanks for the prerelease. On that artifact note, this is a very useful tool: https://nightly.link/phlexplexico/g5ws/workflows/make_release/master closing this and the PR then
