### ISSUE TITLE
G5WS Returns 405 on every match end

### ISSUE THREAD

**Issue by BadSpider1** [PhlexPlexico/G5WS#43]
G5WS Returns the following message
```
L 08/29/2022 - 16:17:59: [G5WS.smx] Failed to find cvar: "get5_backup_path"
L 08/29/2022 - 16:17:59: [G5WS.smx] Request failed, status code = 405
```
I have tried disabling SSL redirects but it had no effects
Unfortunately due to this issue G5V doesnt get any match data

**Comment by PhlexPlexico** [comment]
This shouldn't be an issue with redirects or SSL. The first error is explaining that you're missing `get5_backup_path`. Please make sure you're using the latest nightly of get5, and *update your get5 config* located at `cfg/sourcemod/get5.cfg` as there are new values. Best practice would be to backup your current file and have the plugin recreate the config, and merge in your changes.

This error is because it cannot find the backup file to send to the server to allow for remote backup/restore. This should be done every round, not just end of every match. If it fails, that's fine, the plugin should still work as intended.

**Comment by BadSpider1** [comment]
/csgo/addons/sourcemod/configs/get5.cfg doesnt not exist updated G5WS but that had no effect

**Comment by PhlexPlexico** [comment]
That's not what I'm saying. I'm saying update Get5 first. And that was the wrong path, the path for the config is in `csgo/cfg/sourcemod/get5.cfg`. *Update [get5](https://github.com/splewis/get5/releases/tag/v0.10.0-7c12eae)* and reconfigure its config.

What version of G5WS are you using, and what version of get5 are you using?

**Comment by BadSpider1** [comment]
Im not sure about G5 but G5WS was the latest

the solution was i forgot to install steamworks 

Thanks for help tho, updating G5 fixed the 405 thing
