### ISSUE TITLE
Last map demo isn't being uploaded

### ISSUE THREAD

**Issue by kyoto44** [PhlexPlexico/G5WS#47]
Have no idea what's happened but on the latest release demo from the last map isn't attempted to be uploaded.

```
0|G5API  | POST /match/25/finish 200 18.744 ms - 21
0|G5API  | ::ffff:172.19.0.2 - - [07/Dec/2022:14:40:00 +0000] "POST /match/25/finish HTTP/1.1" 200 21 "-" "Valve/Steam HTTP Client 1.0 (730)"
0|G5API  | POST /match/25/map/2/finish 200 28.454 ms - 21
0|G5API  | ::ffff:172.19.0.2 - - [07/Dec/2022:14:40:00 +0000] "POST /match/25/map/2/finish HTTP/1.1" 200 21 "-" "Valve/Steam HTTP Client 1.0 (730)"

```

**Comment by PhlexPlexico** [comment]
Did you wait for the GoTV delay to finish and upload? The event is fired on `OnDemoFinished`. If you don't wait for the demo to finish and turn off the server, the event will never fire.

**Comment by kyoto44** [comment]
Server isn't being stopped after the match ends, but I will look into gotv delay

**Comment by PhlexPlexico** [comment]
Sounds good. You'll have to wait until the demo is finished recording, and if you're broadcasting the matches it is usually that delay that has to finish in order to flush the demo.  Once it's flushed, the event is triggered and then the demo gets uploaded. You'll see two separate calls (one for the demo name to be updated to the database), then one other that may take longer to upload the actual file via octet-stream :) it's a bit finicky as we've been discovering lately, as libcurl in 32bit must be installed on the game server as well in order to actually transfer the file as well.

**Comment by kyoto44** [comment]
These cvars were already set:
```tv_delaymapchange 1
tv_delay 60```
so have no idea where to look

**Comment by PhlexPlexico** [comment]
Okay so you need to wait 60 seconds before the demo gets flushed and the event fires. If you use `get5_debug 1` and output what you have, there should be some mention of the demo finishing and awaiting upload. See if that fires off and send the logs here if needed :)

**Comment by PhlexPlexico** [comment]
Did this end up working as a solution?
